# Generated by Django 6.0.6 on 2026-06-07 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcquisitionTOFSIMS",
            fields=[
                ("run_id", models.AutoField(primary_key=True, serialize=False)),
                ("run_date", models.DateField()),
                (
                    "software_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slow control EVE", "slow control EVE"),
                            ("Narval", "Narval"),
                            ("C-Visu", "C-Visu"),
                            ("mmass", "mmass"),
                            ("Origin", "Origin"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "software_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "type_acquisition",
                    models.CharField(
                        blank=True,
                        choices=[("local", "local"), ("scan", "scan")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("event_number", models.IntegerField(blank=True, null=True)),
                ("tof_bin_width_ns", models.FloatField(blank=True, null=True)),
                ("number_of_tof_bins", models.IntegerField(blank=True, null=True)),
                (
                    "file_acquisition_log",
                    models.FileField(
                        blank=True, null=True, upload_to="acquisitions/logs/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabUser",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("lab", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreProcessingSpectra",
            fields=[
                (
                    "raw_spectrum_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[("1D", "1D"), ("Map 2D", "Map 2D")], max_length=50
                    ),
                ),
                ("nb_impact", models.IntegerField()),
                (
                    "software_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slow control EVE", "slow control EVE"),
                            ("Narval", "Narval"),
                            ("C-Visu", "C-Visu"),
                            ("mmass", "mmass"),
                            ("Origin", "Origin"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "software_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "filtered_spectrum",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ion_correlated", "ion_correlated"),
                            ("multiplicity_correlated", "multiplicity_correlated"),
                            (
                                "position_detector_correlated",
                                "position_detector_correlated",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "normalized_spectrum",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("analyse_note", models.TextField(blank=True, null=True)),
                (
                    "file_acquisition_log",
                    models.FileField(
                        blank=True, null=True, upload_to="acquisitions/logs/"
                    ),
                ),
                (
                    "acquisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_processings",
                        to="core.acquisitiontofsims",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("sample_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sample_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("batch_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_sample",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sample", "Sample"),
                            ("Substrate", "Substrate"),
                            ("Standard", "Standard"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "material_classification",
                    models.CharField(
                        choices=[
                            ("Ceramic", "Ceramic"),
                            ("Lipids", "Lipids"),
                            ("Metals", "Metals"),
                            ("Micrometeorite", "Micrometeorite"),
                            ("Minerals", "Minerals"),
                            ("Organic", "Organic"),
                            ("Oxides", "Oxides"),
                            ("Polymers", "Polymers"),
                            ("Substrate", "Substrate"),
                            ("Thin organic films", "Thin organic films"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("preparation_date", models.DateField()),
                ("reception_date", models.DateField(blank=True, null=True)),
                (
                    "storage_conditions",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "file_sample",
                    models.FileField(blank=True, null=True, upload_to="samples/pdfs/"),
                ),
                (
                    "file_experiment_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="samples/experiments/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="samples",
                        to="core.labuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrimaryBeam",
            fields=[
                ("irradiation_id", models.AutoField(primary_key=True, serialize=False)),
                ("irradiation_date", models.DateField()),
                (
                    "primary_ion_species",
                    models.CharField(
                        choices=[
                            ("Au +", "Au +"),
                            ("Au2 +", "Au2 +"),
                            ("Au3 +", "Au3 +"),
                            ("Au400 4+", "Au400 4+"),
                        ],
                        max_length=50,
                    ),
                ),
                ("energy_MeV", models.FloatField()),
                (
                    "spot_size_um",
                    models.FloatField(
                        choices=[
                            (100.0, "100 µm"),
                            (200.0, "200 µm"),
                            (400.0, "400 µm"),
                            (800.0, "800 µm"),
                        ]
                    ),
                ),
                ("pulse_beam_kV", models.FloatField()),
                ("repetition_rate_kHz", models.FloatField()),
                (
                    "accelerator_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ion_source_type",
                    models.CharField(
                        blank=True,
                        choices=[("Liquid metal", "Liquid metal"), ("ECR", "ECR")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("fluence_ions_cm2", models.FloatField(blank=True, null=True)),
                ("current_nA", models.FloatField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "file_accelerator_log",
                    models.FileField(blank=True, null=True, upload_to="beams/logs/"),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irradiations",
                        to="core.sample",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spectra",
            fields=[
                ("mz_spectra_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_mz_spectra", models.DateField()),
                ("expert_validation", models.BooleanField(default=False)),
                ("file_tag", models.FileField(upload_to="spectra/tags/")),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "software_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slow control EVE", "slow control EVE"),
                            ("Narval", "Narval"),
                            ("C-Visu", "C-Visu"),
                            ("mmass", "mmass"),
                            ("Origin", "Origin"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "software_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "file_peak_label",
                    models.FileField(
                        blank=True, null=True, upload_to="spectra/peak_labels/"
                    ),
                ),
                (
                    "file_peak_list",
                    models.FileField(
                        blank=True, null=True, upload_to="spectra/peak_lists/"
                    ),
                ),
                (
                    "file_result",
                    models.FileField(
                        blank=True, null=True, upload_to="spectra/results/"
                    ),
                ),
                (
                    "pre_processing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectra",
                        to="core.preprocessingspectra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spectrometer",
            fields=[
                (
                    "spectrometer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("spectrometer_date", models.DateField()),
                (
                    "analyser_type",
                    models.CharField(
                        choices=[("direct", "direct"), ("reflecteur", "reflecteur")],
                        max_length=50,
                    ),
                ),
                ("lens_ext", models.FloatField()),
                ("lens_SI", models.FloatField()),
                ("detector_bias", models.FloatField()),
                ("sample_bias_kV", models.FloatField()),
                (
                    "polarity",
                    models.CharField(
                        choices=[("Positive", "Positive"), ("Negative", "Negative")],
                        max_length=20,
                    ),
                ),
                (
                    "instrument_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "name_position",
                    models.CharField(
                        blank=True,
                        choices=[("Substrate", "Substrate"), ("Target", "Target")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("analysis_area_um2", models.FloatField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "file_slowcontrol_log_txt",
                    models.FileField(
                        blank=True, null=True, upload_to="spectrometers/logs/"
                    ),
                ),
                ("spectrometer_metadata", models.JSONField(blank=True, null=True)),
                (
                    "primary_beam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrometers",
                        to="core.primarybeam",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="acquisitiontofsims",
            name="spectrometer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acquisitions",
                to="core.spectrometer",
            ),
        ),
    ]
