# Generated by Django 6.0.6 on 2026-06-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acquisitiontofsims",
            options={
                "verbose_name": "Acquisition TOF-SIMS",
                "verbose_name_plural": "Acquisitions TOF-SIMS",
            },
        ),
        migrations.AlterModelOptions(
            name="laboratory",
            options={"verbose_name_plural": "Laboratories"},
        ),
        migrations.AlterModelOptions(
            name="spectra",
            options={"verbose_name_plural": "Spectra"},
        ),
        migrations.AddField(
            model_name="user",
            name="file_proposal",
            field=models.FileField(blank=True, null=True, upload_to="users/proposals/"),
        ),
    ]
