# Generated by Django 6.0.6 on 2026-07-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acquisitiontofsims",
            name="equipment",
        ),
    ]
