# Generated by Django 6.0.6 on 2026-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_acquisitiontofsims_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitiontofsims',
            name='run_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
