# Generated by Django 6.0.6 on 2026-07-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_acquisitiontofsims_run_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='spectrometerparameters',
            options={'verbose_name_plural': 'Spectrometer Parameters'},
        ),
    ]
