# Generated by Django 6.0.6 on 2026-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sample_file_experiment_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='reception_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
