# Generated by Django 6.0.6 on 2026-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='reflectron_state',
            field=models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='primarybeam',
            name='source_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='analyser_type',
            field=models.CharField(choices=[('TOF', 'TOF')], max_length=50),
        ),
    ]
