# Generated by Django 6.0.6 on 2026-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sample_reception_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confidentiality',
            field=models.CharField(max_length=1),
        ),
    ]
