# Generated by Django 6.0.6 on 2026-06-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_confidentiality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confidentiality',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
