# Generated by Django 6.0.6 on 2026-07-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_equipment_reflectron_state_primarybeam_source_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarybeam',
            name='source_mode',
        ),
        migrations.AddField(
            model_name='primarybeam',
            name='source_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
