# Generated by Django 6.0.6 on 2026-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_confidentiality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confidentiality',
            field=models.BooleanField(default=False),
        ),
    ]
